### PR TITLE
Connected clients should know their own latency

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Where is this to be exercised?

**Comment by AudriusButkevicius** [comment]
Also, this will be much more than the osutil.TCPPing as we do the handshake an all other crap in connect(), so for high latency links it will be multiples of the real value which can matter.

**Comment by calmh** [comment]
The new discovery checks for ok-status and latency on each announce. Actually retesting on each announce is wasteful if we already know it. My next step would be to populate this from the periodic ping I was envisioning - it's just that the ping currently is in the wrong direction for the client to know the latency.

I know we're measuring something different here than just a connect, but I don't think it matters as long as we're only comparing values of the same type.

**Comment by AudriusButkevicius** [comment]
Well even a ping will not be a value of the same type as this, as this is atleast a few RTT's. Move latency check around Dial.

**Comment by calmh** [comment]
Is there a risk that the value from Dial is out of date and meaningless 12 hours or 12 days later?

**Comment by AudriusButkevicius** [comment]
I guess it could be, if we've switched networks, but in that case we could redial.
I don't think we should suddenly switch relays if the network conditions change.

**Comment by calmh** [comment]
No I was more thinking we should provide up to date info in our announcement if network conditions change, but it we don't switch relays it doesn't actually matter.

I still want the actual relay client to know this info though, so it can be asked about it instead of us having to dial-check from the outside each time, I'll hack the PR appropriately.

**Comment by AudriusButkevicius** [comment]
All I was suggesting is to move the benchmarking c.latency value around the Dial method, rather than connect, which does Dial, sets tcp options, handshakes, etc.

**Comment by calmh** [comment]
Yep :+1:

**Comment by calmh** [comment]
Please take another look.

**Pull request merged**
