### PR TITLE
Jail the whole thing a bit more

### PR DESCRIPTION
**Pull request by rumpelsepp**
Add WorkingDirectory to create and use the certificates within
/var/lib/syncthing-relaysrv. Add RootDirectory to chroot(2) the whole
thing into that directory.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
The only comment I have, is that the build.sh produces relaysrv not syncthing-relaysrv.

**Comment by rumpelsepp** [comment]
Oh; on arch linux we prefix all syncthing stuff with `syncthing-`. We could change this upstream in the service file and I could just patch that with `sed` in the package.

**Comment by AudriusButkevicius** [comment]
Actually, I'd rather modify the build script to produce syncthing-relaysrv

**Comment by AudriusButkevicius** [comment]
Ok, I withdraw that. Given we call discosrv discosrv, we should keep this as relaysrv, and I think you should just sed it as part of the packaging process.

**Comment by rumpelsepp** [comment]
> I think you should just sed it as part of the packaging process.

Yeah, no problem.

**Pull request merged**
